services:

* type: web
  name: project-foresight-api
  runtime: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: python -m uvicorn api:app --host 0.0.0.0 --port $PORT
